
.SUFFIXES:
.SUFFIXES:  .o .C

SRCS :=$(wildcard *.C)
OBJS_SRC=$(SRCS:.C=.o)
OBJS := $(notdir $(OBJS_SRC))

CXX=icpc
LDFLAGS=-qopenmp 
#FPMODEL=-fp-model consistent
FPMODEL=
CXXFLAGS=-march=core-avx2 -O3 $(FPMODEL) -qopenmp -DOPT=float


BIN=evd

$(BIN): $(OBJS)
	$(CXX) $(OBJS) $(LDFLAGS) -o $(BIN)

.C.o:
	$(CXX) -o $@ $(CXXFLAGS) -c $<

clean:
	rm -f *.o  $(BIN)
