#!/bin/bash

#grep ressqr log-4.4.3.4 > ressqr-4.4.3.4
#grep ressqr log-3.3.3.3 > ressqr-3.3.3.3
#grep ressqr log-2.2.3.2 > ressqr-2.2.3.2

#grep "nkeep_residuum" log64-4.4.4.4 > res64-4.4.4.4
#grep "evec_residuum" log64-4.4.4.4 > ressqr64-4.4.4.4

#cat compare.4.4.3.4.100 | awk '{ if (NF>2) { print $2, $10, substr($5,3)+0.0 } }' > compare.4.4.3.4.100.dat
#cat compare.4.4.3.4.0 | awk '{ if (NF>2) { print $2, $10, substr($5,3)+0.0 } }' > compare.4.4.3.4.0.dat


#tail -n +2 /hpcgpfs01/work/clehner/results-196/huge-data-lanc/eigen-values.txt > ev.dat

gnuplot<<EOF

set terminal postscript color enhanced
set output 'plots.ps'

set logscale y



set yrange [*:1]
set title "Residuum^2 of evec n+1 when reconstructed from blocked 1..n"
set xlabel "n"

plot 'res-4.4.3.4' using 2:4 title "48^3, 4.4.3.4 block", \
'res-2.2.3.2' using 2:4 title "48^3, 2.2.3.2 block",\
'res64-4.4.4.4' using 2:4  title "64^3, 4.4.4.4 block"

#'res-3.3.3.3' using 2:4 title "48^3, 3.3.3.3 block",\
#'res-3.3.3.3-567' using 2:4  title "48^3, 3.3.3.3 block alt.config", \

set title "Residuum^2 of evec n when reconstructed from blocked 1..400"
plot 'ressqr-4.4.3.4' using 2:5  title "48^3, 4.4.3.4 block", \
'ressqr-2.2.3.2' using 2:5  title "48^3, 2.2.3.2 block",\
'ressqr64-4.4.4.4' using 2:4 title "64^3, 4.4.4.4 block"

#'ressqr-3.3.3.3' using 2:5  title "48^3, 3.3.3.3 block",\

set title "48^3 eigenvalue distribution"
plot 'ev.dat' notitle

set title "Norm of difference / norm of eigenvector (original - compressed)"
set yrange [1e-16:1]
plot\
 'compare.4.4.3.4.100.dat' using 1:(\$2/\$3) title "48^3, 4.4.3.4 - nsingle_prec = 100; 15%", \
 'compare.4.4.3.4.0.dat' using 1:(\$2/\$3) title "48^3, 4.4.3.4 - nsingle_prec = 0; 12%"

set yrange [1e-8:1]
set title "Effect on CG convergence on 48^3 ensemble 980"
plot\
 'res-48c-test/77-cg.dat' title "Original", \
 'res-48c-test/99-cg.dat' title "Compressed" lt 3

unset logscale y
set xrange [-0.5:35.5]

set yrange [*:*]
set title "Effect on single point source C(t) t^4 on 48^3 ensemble 980"
plot\
 'res-48c-test/77-l.dat' using 1:(\$2*\$1**4) title "Original low-appx" lt 1, \
 'res-48c-test/99-l.dat' using 1:(\$2*\$1**4) title "Compressed low-appx" lt 4, \
 'res-48c-test/77-sl.dat' using 1:(\$2*\$1**4) title "Original sloppy" lt 7, \
 'res-48c-test/99-sl.dat' using 1:(\$2*\$1**4) title "Compressed sloppy" lt 3

set title "Effect on full low-mode reconstruction C(t) t^4 on 48^3 ensemble 980"
plot\
 'res-48c-test/77-g0g0-low3.dat' using 1:(\$2*\$1**4) title "Original", \
 'res-48c-test/99-g0g0-low3.dat' using 1:(\$2*\$1**4) title "Compressed" lt 3

EOF

ps2pdf plots.ps
