#!/bin/bash
# These are single-node jobs
# every single job should do $N files

N=16 # needs 1 hour

source /soft/compilers/intel/bin/compilervars.sh --arch intel64

ddd=/home/lehner/eigen-comp/compress
data=/projects/HadronicLight_2/clehner/evec-cache/48I

x=4
y=4
z=3
t=4
nsin=100

nn=0
for results in $data/results-*
do

    if [ ! -f $results/compression-complete ];
    then

	runLayout=$(head -n 1000 /home/ljin/application/Public/Muon-GM2-cc/jobs/48I/runs/3/$(basename $results)/*.output | 
	grep "Physical XxY" | awk '{ print $5 }' | awk 'BEGIN{ FS="x" }{ print 48/$1 " " 48/$2 " " 48/$3 " " 96/$4 }')

	if [[ "$runLayout" != "12 12 6 12" ]];
	then
	    echo "Unknown run layout for $results: $runLayout"
	else

	    nc=0
	    for ((i=0;i<1024;i++));
	    do
		
		di=$(awk "BEGIN{ printf(\"%2.2d\", int($i/32) ); }")
		ei=$(awk "BEGIN{ printf(\"%10.10d\", $i ); }")
		
		fn=${results}/huge-data-lanc/${di}/${ei}

		if [ -f $fn ];
		then
		    sz=$(ls -l $fn | awk '{ print $5/9953280000 }')
		else
		    sz=0
		fi
		    
		if [ ! -f $fn.compressed ];
		then
				    
		    if ((nn<N));
		    then

			if [[ "$sz" == "1" ]];
			then
			    touch $fn.compressed

			    echo "File ready to be compressed $fn"
			    cd ${results}/huge-data-lanc
			    ${ddd}/evc 12 12 6 12 10 $x $y $z $t 10 400 ${i} 32 1 $nsin 0 0 > $fn.compressed.log
			    nn=$((nn+1))
			    nc=$((nc+1))
			fi

		    fi
#idx=$i
#cd ${data}
#
		else
		    nc=$((nc+1))
		fi
	    done
	    
	    if [[ "$nc" == "1024" ]];
	    then
		date > $results/compression-complete
	    fi
	    
	fi

    fi
done


